[webserver]
web-target ansible_host=webserver.infra ansible_user=lexuswang ansible_become_pass=lexuswang

[dbserver]
db-target ansible_host=dbserver.infra ansible_user=lexuswang ansible_become_pass=lexuswang

[webserver:vars]
ansible_python_interpreter=/usr/bin/python3

[dbserver:vars]
ansible_python_interpreter=/usr/bin/python3
